name: 'Execute ApiBee runner'
description: 'ApiBee runner GitHub Action'
inputs:
  image:
    description: 'ApiBee Docker image.'
    required: true
    default: 'itbusina/apibee:latest'
  args:
    description: 'The ApiBee arguments.'
    required: true
  input_dir:
    description: 'The path to a directory with collection(s).'
    required: false
    default: 'test'
  network:
    description: 'The container network.'
    required: false
    default: 'host'

runs:
  using: "composite"
  steps:
    - name: Execute ApiBee
      shell: bash
      run: |
        docker run \
          -v ${{ inputs.input_dir }}:/app/${{ inputs.input_dir }} \
          --rm \
          --network=${{ inputs.network }} \
          ${{ inputs.image }} \
          ${{ inputs.args }}
