name: 'Execute ApiBee runner'
description: 'ApiBee runner GitHub Action'
inputs:
  image:
    description: 'Docker image.'
    required: true
  args:
    description: 'The ApiBee arguments.'
    required: true
  input_dir:
    description: 'The path to a directory with collection(s).'
    required: false
    default: .
  output_dir:
    description: 'The directory path to save the report(s).'
    required: false
  network:
    description: 'The container network.'
    required: false
    default: 'apibee'

runs:
  using: "composite"
  steps:
    - name: Execute ApiBee
      shell: bash
      run: |
        docker network create apibee
        docker run \
          -v ${{ inputs.input_dir }}:/app/${{ inputs.input_dir }} \
          -v ${{ inputs.output_dir }}:/app/${{ inputs.output_dir }} \
          --rm \
          --network=${{ inputs.network }} \
          ${{ inputs.image }} \
          dotnet apibee.dll ${{ inputs.args }}
