name: 'Execute ApiBee runner'
description: 'ApiBee runner GitHub Action'
inputs:
  image:
    description: 'ApiBee Docker image.'
    required: true
    default: 'kbahdanovich/apibee:latest'
  args:
    description: 'The ApiBee arguments.'
    required: true
  input_dir:
    description: 'The path to a directory with collection(s).'
    required: false
    default: .
  output_dir:
    description: 'The directory path to save the report(s).'
    required: false

runs:
  using: "composite"
  steps:
    - name: Execute ApiBee
      shell: bash
      run: |
        docker run \
          -v ${{ inputs.input_dir }}:/app/${{ inputs.input_dir }} \
          -v ${{ inputs.output_dir }}:/app/${{ inputs.output_dir }} \
          ${{ inputs.image }} \
          ${{ inputs.args }}
